// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqbhgonzdpehefedmlmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xYmhnb256ZHBlaGVmZWRtbG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0OTE5MzcsImV4cCI6MjA1NTA2NzkzN30.DilvPrugTwWZp2FXt03YsZnKFg0QVj6DKeo0UuNryAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);